# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push backend
      inputs:
        containerRegistry: 'docker hub technofront'
        repository: 'augustech/k8s_api_deploy_back'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Back/dockerfile'
    - task: Docker@2
      displayName: Build and push DB
      inputs:
        containerRegistry: 'docker hub technofront'
        repository: 'augustech/k8s_api_deploy_db'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Db/dockerfile'
    - task: Docker@2
      displayName: Build and push frontend
      inputs:
        containerRegistry: 'docker hub technofront'
        repository: 'augustech/k8s_api_deploy_front'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Front/dockerfile'
